# Using Tensorflow like Numpy
A tensor is usually  a multidimentional array (exactly like a NumPy ndarray), but it can also hold a scalar value( such as 13 ). The tensor will be important when we create custom cost functions, custom metrics, custom layers, and more.

In [2]:
import tensorflow as tf

In [3]:
tf.constant([[1, 2, 3], [4, 5, 6]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [4]:
tf.constant(13)

<tf.Tensor: shape=(), dtype=int32, numpy=13>

In [5]:
t = tf.constant([[1, 2, 3], [4, 5, 6]])
t.shape

TensorShape([2, 3])

In [6]:
t.dtype

tf.int32

### Indexing works much like in NumPy

In [7]:
t[:, 1:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]], dtype=int32)>

In [8]:
t[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[2],
       [5]], dtype=int32)>

# All sort of tensor operations are available

In [9]:
t + 10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]], dtype=int32)>

In [10]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)>

In [11]:
# @ for matrix multiplication
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

there are lot of math operations you need!!!! c Hands on ML